// sigil: REPAIR
export { default as ModuleCard } from './ModuleCard'
export { default as SectionRail } from './SectionRail'
export { default as ThemeSwitcher } from './ThemeSwitcher'
export { default as MetricPill } from './primitives/MetricPill'
export { default as LineList } from './primitives/LineList'
export { default as ArdaErrorBoundary } from './core/ArdaErrorBoundary'
export { default as ArdaHeader } from './core/ArdaHeader'
export { default as PresencePanel } from './core/PresencePanel'
export { default as LayoutEditor } from './core/LayoutEditor'
export { default as PanelWorkspace } from './core/PanelWorkspace'
export { default as SceneWorkstation } from './core/SceneWorkstation'
export { default as SceneTransitionOverlay } from './core/SceneTransitionOverlay'
export { default as SceneBackdrop } from './core/SceneBackdrop'
export { default as SignalField } from './core/SignalField'
export { default as RuntimeModeBadge } from './core/RuntimeModeBadge'
export { default as ExecutiveOverviewModule } from './modules/ExecutiveOverviewModule'
export { default as SectionFocusModule } from './modules/SectionFocusModule'
export { default as HumanRealmModule } from './modules/HumanRealmModule'
export { default as ArandurApprovalWorkstation } from './modules/ArandurApprovalWorkstation'
export type { ArandurQueueWriteRequest, HumanAugmentationApproval } from './modules/ArandurApprovalWorkstation'
export { default as ReviewGateWorkstation } from './modules/ReviewGateWorkstation'
export { buildReviewGateDecisionRecordPreview } from './modules/ReviewGateWorkstation'
export type { ReviewGateDecisionStatus, ReviewGateItem } from './modules/ReviewGateWorkstation'
export { default as HermesDashboardModule } from './modules/HermesDashboardModule'
export { default as QueueProvenancePanel } from './modules/QueueProvenancePanel'
export { default as SourceActionContractPanel } from './modules/SourceActionContractPanel'
export { default as PlanningActionContractPanel } from './modules/PlanningActionContractPanel'
export { buildPlanningTaskPivotPreview } from './modules/PlanningActionContractPanel'
export { default as OperationsActionContractPanel } from './modules/OperationsActionContractPanel'
export { buildOperationsActionContracts } from './modules/OperationsActionContractPanel'
export { default as WorldTerminalActionContractPanel } from './modules/WorldTerminalActionContractPanel'
export { buildWorldTerminalActionContracts } from './modules/WorldTerminalActionContractPanel'
export { default as OperatingSurfacePlanModule } from './modules/OperatingSurfacePlanModule'
export type { CommandConsoleSurface, LiveRuntimeChannelEvidence, OperatingSurfaceLaneReport } from './modules/OperatingSurfacePlanModule'
export { default as SystemsModule } from './modules/SystemsModule'
export type { OperatorCockpitSurface } from './modules/systems/OperatorCockpitPanel'
export { default as ServiceEmbedModule } from './modules/ServiceEmbedModule'
export { default as MediaLibraryModule } from './modules/MediaLibraryModule'
export { default as SourceCoverageBadge } from './modules/SourceCoverageBadge'
export type { SourceCoverageBadgeState } from './modules/SourceCoverageBadge'
export { default as SourceFreshnessStrip } from './modules/SourceFreshnessStrip'
export { default as FleetHealthPanel } from './modules/systems/FleetHealthPanel'
export { default as RoutingOwnershipPanel } from './modules/systems/RoutingOwnershipPanel'
export { default as RoutingActionContractPanel } from './modules/systems/RoutingActionContractPanel'
export { buildRoutingActionContract } from './modules/systems/RoutingActionContractPanel'
export { default as LaneHeadroomPanel } from './modules/systems/LaneHeadroomPanel'
export { default as LaneFitnessPanel } from './modules/systems/LaneFitnessPanel'
export { default as RoutableProvidersPanel } from './modules/systems/RoutableProvidersPanel'
export { default as AgentRosterPanel } from './modules/systems/AgentRosterPanel'
export { default as BusinessModule } from './modules/BusinessModule'
export { default as PersonalGrowthModule } from './modules/PersonalGrowthModule'
export { default as SettingsModule } from './modules/SettingsModule'
export type { ModuleId, ThemeId, ThemeOption, ViewMode, MonitorAssignment } from './core/types'

export { default as LearningLoopSurface } from './modules/LearningLoopSurface'
export { default as LearningLoopSurfaceWrapper } from './modules/LearningLoopSurfaceWrapper'
